drugs = {
    --{ name, data = { accountDataName, Image Directory, Description}},
    --{ name = "", data = { accD = "", img = ""}},
    --{ name = "Acid", data = { "NumCoke", "Acid", "Causes disturbed vision as well as hallucinations.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    --{ name = "Adderall", data = { "NumAdd", "Adderal", "Increases your accuracy when in combat.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    { name = "Cocaine", data = { "NumCoke", "Cocaine", "You will recieve less damage.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    --{ name = "Ecstasy", data = { "NumX", "Ecstasy", "Makes you stronger, and take less damage.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    --{ name = "LSD", data = { "NumLSD", "LSD", "gaga", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    --{ name = "Crystal Meth", data = { "NumMeth", "Meth", "Able to see through walls.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    --{ name = "PCP", data = { "NumPCP", "PCP", "Increased strength.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    { name = "Weed", data = { "NumWeed", "Weed", "Makes you move slower, and gives the munchies.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    --{ name = "Oxycodone", data = { "NumOxy", "Oxycodone", "Gives you 200 health points.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    { name = "Marijuana", data = { "NumMari", "Marijuana", "Makes you move slower.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    { name = "Tylenol", data = { "NumTyl", "Tylenol", "Makes your screen blur.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
    { name = "Meth", data = { "NumMeth", "Meth", "Increases your weapon accuracy.", "Drug Lab Raids, Hospital Raids, Purchase, Drug Trafficking, Heists, Pharmacy Raids, Cartel"}},
}
